# Generated by Django 3.2.8 on 2021-12-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_img',
            field=models.ImageField(default='/media/users/basicUser.png', upload_to='users'),
        ),
    ]
