# Generated by Django 3.2.7 on 2021-10-10 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_location', models.FloatField()),
                ('y_location', models.FloatField()),
                ('location_name', models.TextField()),
            ],
            options={
                'db_table': 'mapLocations',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_location', models.FloatField()),
                ('y_location', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('picture', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            options={
                'db_table': 'pictures',
            },
        ),
    ]
