# Generated by Django 3.2.8 on 2021-12-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='contents',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
